### ISSUE TITLE
migration does not correctly identify table name for camelcased classes

### ISSUE THREAD

**Issue by asoules** [rich/acts_as_revisable#1]
When I ran the migration script:
"script/generate revisable_migration WorkshopSignup"

the migration table was workshopsignups, rather than workshop_signups. The file name for the migration was also missing the underscore.

Awesome gem otherwise!! :)

**Comment by ozzyaaron** [comment]
It looks like the gem install installs an old version of this gem, if you clone it you get a working version. This has happened for me twice. I went and fixed it and then when I went to merge my changes I realised they were already there!!
