### ISSUE TITLE
validates_uniqueness_of does not work correctly

### ISSUE THREAD

**Issue by rich** [rich/acts_as_revisable#3]
This is due to all records being stored in the same table. Need to investigate scoping it automatically.

Originally reported in http://chrisblunt.com/blog/2009/08/06/rails-validating-unique-attributes-with-acts_as_revisable/

**Comment by skgma** [comment]
I've been doing this as a sort of default in my classes.  It can make sense to not include this and to simply note that that should be done, as you don't want to alter the behavior of validates_uniqueness_of without informing the user.

I would like to note something further about this issue.  My XYZRevision class has the following:

validates_uniqueness_of :name, :scope => [:revisable_original_id, :revisable_number, :revisable_is_current]

It's perhaps not necessary to even have this in a Revision class.  But I wanted to ensure that I was importing/updating data correctly.

Furthermore, it is necessary to specify this if you are doing Single-Table Inheritance and your parent table has a validates_uniqueness_of statement.  I'm not sure if we can reset this in a child model--but that's liable to throw people off.

**Comment by rich** [comment]
This is fixed. Here are my comments originally posted to the blog post mentioned above:

This happened because ActiveRecord ignores the default scope of a class in the validates_uniqueness_of method. I’m not really sure why but, I’m sure there’s a good reason.

AAR now overrides that method by default and makes sure to properly scope it. You can disable this new behavior by passing “:no_validation_scoping => true” in your acts_as_(revisable|revision) calls.

This is in the latest gem which is 1.1.1 as of this post.
