### ISSUE TITLE
Record current_user for revisions

### ISSUE THREAD

**Issue by cjk** [rich/acts_as_revisable#9]
I'm a happy AAR user, but one missing feature keeps bugging me: I'd like to be able to record what user was responsible for a certain revision. That'd be as simple as saving current_user() as a revision-attribute or something.
Possible? Planned?

**Comment by rich** [comment]
Well, it being so easy to do is actually the reason I haven't added it. Something like:

```
before_revise :grab_current_user

def grab_current_user
  self[:revised_by] = User.current
end
```

So, that's been my response to this request several times. That said, I'm working on a set of common AAR extensions that will be a standard part of the plugin. This pattern is one of those extensions. I hope to make a release in the next couple of weeks. It'll likely show up in the repo sooner.

**Comment by cjk** [comment]
> self[:revised_by]

I wasn't aware of "revised_by". In that case it's really easy and I'll give it a shot.

> That said, I'm working on a set of common AAR extensions that will be a
> standard part of the plugin.

Thanks, that would be great and would probably make the feature's application for obvious.

**Comment by rich** [comment]
Oh, no, revised_by doesn't exist by default. You would have to add that column.
